name: Deploy NickDemoProd

on: 
  workflow_run: 
    workflows: ["Pack NickDemoProd"] 
    branches: [main] 
    types: 
      - completed 
  workflow_dispatch: 
env:
#edit your values here
  ENVIRONMENT_URL: 'https://orgf65c2582.crm6.dynamics.com' 
  CLIENT_ID: 'c58a2ae4-ee2f-4dde-977a-9c1023743637'
  TENANT_ID: 'd1ee9b37-cae3-4945-a777-7b8b03047391'
jobs: 
  deploy: 
    runs-on: windows-latest 
    environment: production 
    steps: 
      - uses: dawidd6/action-download-artifact@v2 
        with: 
          workflow: pack-solution.yml 
          name: packed-solution 
      - uses: microsoft/powerplatform-actions/import-solution@v0 
        with: 
          environment-url:  ${{env.ENVIRONMENT_URL}}
          app-id: ${{env.CLIENT_ID}}
          client-secret: ${{ secrets.PowerPlatformSPN }} 
          tenant-id: ${{env.TENANT_ID}}
          solution-file: GithubActionsPipeline‎.zip 
